artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  data_name: "Chicken-fecal-images"


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model_weights.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated_weights.keras


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model_weights.keras

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model_trained_weights.keras

evaluation:
  unzip_dir: artifacts/data_ingestion
  data_name: "Chicken-fecal-images"
  trained_model_path: artifacts/training/model_trained_weights.keras